# =========================================================
# Stage 1: Install repository
# =========================================================
FROM {{ .spec.git.image.repo }}:{{ .spec.git.image.version }} AS install

RUN git clone \
  --depth {{ .spec.git.clone.depth }} \
  --revision {{ .spec.cardinal.source.github.rev }} \
  https://github.com/{{ .spec.cardinal.source.github.owner }}/{{ .spec.cardinal.source.github.repo }}{{ if gt (len .spec.git.cleanup.paths) 0 }}; \
  && rm -rf \
  {{ conv.Join .spec.git.cleanup.paths " \\\n  " }}
  {{- end }}

# =========================================================
# Stage 2: Build
# =========================================================
{{ tmpl.Exec "build" . }}

# =========================================================
# Stage 3: Finalize
# =========================================================
{{ tmpl.Exec "final" . }}
