name: Automatic update cardinal version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

defaults:
  run:
    shell: nix develop .#ci --fallback --command bash -e {0}

jobs:
  detect-new-tags:
    runs-on: ubuntu-latest
    outputs:
      new_tags: ${{ steps.compare_tags.outputs.new_tags }}
      raw_tags: ${{ steps.get_tags.outputs.raw_tags }}
    env:
      TAGS_COUNT: 10
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: NixOS/nix-installer-action@v1

      - name: Get tags
        id: get_tags
        run: |
          TAGS=$(curl https://api.github.com/repos/sidor0912/FunPayCardinal/tags?per_page=$TAGS_COUNT)
          NAMES=$(jq -r '.[].name' <<< "$TAGS")

          echo "TAGS_RAW: $TAGS"
          echo "TAGS_NAMES: $NAMES"

          echo "raw_tags=$(echo "$TAGS" | jq -c -r)" >> $GITHUB_OUTPUT
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$NAMES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Restore processed tags
        uses: actions/cache@v5
        with:
          path: .cache/tags
          key: processed-tags-${{ hashFiles('spec.json') }}
          restore-keys: |
            processed-tags-

      - name: Compare tags
        id: compare_tags
        run: |
          mkdir -p .cache/tags

          PROCESSED_TAGS_FILE=".cache/tags/processed-tags-${{ hashFiles('spec.json') }}"
          GET_TAGS="${{ steps.get_tags.outputs.tags }}"

          echo "GET_TAGS: $GET_TAGS"
          echo "PROCESSED TAGS: $(cat "$PROCESSED_TAGS_FILE")"

          if [[ -s $PROCESSED_TAGS_FILE ]]; then
            TAGS=$((echo "$GET_TAGS" | grep -v -F -f "$PROCESSED_TAGS_FILE") || echo "")
          else
            touch $PROCESSED_TAGS_FILE
            TAGS=$(echo "$GET_TAGS")
          fi

          if [[ -z $TAGS ]]; then
            echo "New tags not found"
            exit 0
          fi
          echo "COMPARED TAGS: $TAGS"

          echo "$TAGS" | head -n 10 > "$PROCESSED_TAGS_FILE"

          JSON_TAGS=$(echo "$TAGS" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "JSON_TAGS: $JSON_TAGS"
          echo "new_tags=$JSON_TAGS" >> $GITHUB_OUTPUT

  update:
    needs: detect-new-tags
    if: |
      needs.detect-new-tags.result == 'success' &&
      needs.detect-new-tags.outputs.new_tags != '' &&
      needs.detect-new-tags.outputs.new_tags != '[]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        tag: "${{ fromJson(needs.detect-new-tags.outputs.new_tags) }}"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: NixOS/nix-installer-action@v1

      - name: Update to ${{ matrix.tag }}
        run: |
          VERSION="${{ matrix.tag }}"
          RAW_TAGS='${{ needs.detect-new-tags.outputs.raw_tags }}'
          REVISION=$(jq --arg ver $VERSION -r '.[] | select(.name == $ver) | .commit.sha' <<< "$RAW_TAGS")

          just update-version "${VERSION#v}" "$REVISION"

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "ci(update): automatic update cardinal to ${{ matrix.tag }}"
          title: "ci(update): automatic update cardinal to ${{ matrix.tag }}"
          body: "This PR is created automatically by github actions workflow"
          branch: ci-update-${{ matrix.tag }}
          base: main
          sign-commits: true
