name: Docker image push

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

defaults:
  run:
    shell: nix develop .#ci --fallback --command bash -e {0}

jobs:
  push:
    if: |
      github.event.pull_request.merged == true || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        target:
          - alpine
          - distroless
          - slim-bookworm
          - slim-trixie
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: NixOS/nix-installer-action@v1

      - name: Get cardinal version
        id: cardinal_version
        run: |
          CARDINAL_VERSION=$(jq -r '.cardinal.version' spec.json)
          echo "version=$CARDINAL_VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: shotplay
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Set up QEMU
        uses: docker/setup-qemu-action@v4.2.0
        with:
          platforms: amd64,arm64,arm,ppc64le,riscv64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/bake-action@v7
        with:
          push: true
          targets: ${{ matrix.target }}-cross
          files: versions/${{ steps.cardinal_version.outputs.version }}/docker-bake.hcl
