name: Automatic update cardinal version

permissions:
    contents: write
    pull-requests: write

on:
    workflow_dispatch: null
    schedule:
        - cron: "0 */6 * * *"

jobs:
    detect-new-tags:
        runs-on: ubuntu-latest
        outputs:
            new_tags: ${{ steps.compare.outputs.new_tags }}
        steps:
            - uses: actions/checkout@v7

            - name: Get tags
              run: |
                  PER_PAGE=10
                  TAGS_JSON_FILE="/tmp/tags.json"

                  curl -sS https://api.github.com/repos/sidor0912/FunPayCardinal/tags?per_page=$PER_PAGE -o "$TAGS_JSON_FILE"

                  if [[ ! -f "$TAGS_JSON_FILE" ]]; then
                    echo "Failed get tags"
                    exit 1
                  fi

                  echo "TAGS JSON FILE: $(cat "$TAGS_JSON_FILE")"

            - name: Restore processed tags
              uses: actions/cache@v5
              id: cache_tags
              with:
                  path: .cache/tags
                  key: processed-${{ github.run_id }}
                  restore-keys: |
                      processed-

            - name: Compare tags
              id: compare
              run: |
                  mkdir -p .cache/tags

                  PROCESSED_FILE=".cache/tags/processed.txt"
                  PROCESSED_FILE_TMP="/tmp/processed.txt"
                  TAGS_JSON_FILE="/tmp/tags.json"
                  TAGS_FILE="/tmp/tags.txt"
                  NEW_TAGS=false

                  cat "$TAGS_JSON_FILE" | jq -r '.[].name' > "$TAGS_FILE"

                  echo "TAGS: $(cat "$TAGS_FILE")"

                  if [[ -s $PROCESSED_FILE ]]; then
                  TAGS=$(cat "$TAGS_FILE" | grep -v -F -f $PROCESSED_FILE || echo "")
                  else
                    touch $PROCESSED_FILE
                    TAGS=$(cat "$TAGS_FILE")
                  fi

                  echo "PROCESSED: $(cat "$PROCESSED_FILE")"

                  echo "$TAGS" > $PROCESSED_FILE_TMP
                  cat "$PROCESSED_FILE" >> $PROCESSED_FILE_TMP
                  head -n 10 "$PROCESSED_FILE_TMP" | tee $PROCESSED_FILE > /dev/null

                  echo "NEW PROCESSED: $(cat "$PROCESSED_FILE")"

                  JSON_TAGS=$(echo "$TAGS" | jq -R -s -c 'split("\n") | map(select(. != ""))')
                  echo "new_tags=$JSON_TAGS" >> $GITHUB_OUTPUT

                  echo "JSON TAGS: $JSON_TAGS"

    update:
        needs: detect-new-tags
        if: |
            needs.detect-new-tags.result == 'success'
            && needs.detect-new-tags.outputs.new_tags != ''
            && needs.detect-new-tags.outputs.new_tags != '[]'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                tag: "${{ fromJson(needs.detect-new-tags.outputs.new_tags) }}"
        steps:
            - uses: actions/checkout@v7

            - name: Update for ${{ matrix.tag }}
              run: |
                  CONFIG_FILE=config.json
                  jq --arg ver ${{ matrix.tag }} '.cardinal_version=$ver' $CONFIG_FILE > $CONFIG_FILE

                  echo "CONFIG: $(cat $CONFIG_FILE)"
                  chmod +x update.sh
                  ./update.sh

            - name: Create PR
              uses: peter-evans/create-pull-request@v8
              with:
                  commit-message: "ci(update.sh): automatic update to ${{ matrix.tag }}"
                  title: "Automatic update to ${{ matrix.tag }}"
                  body: "This PR is created automatically by workflow"
                  branch: auto-update-${{ matrix.tag }}
                  base: main
                  sign-commits: true
